/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    'contact': RouteRecordInfo<'contact', '/contact', Record<never, never>, Record<never, never>>,
    'info-query': RouteRecordInfo<'info-query', '/info-query', Record<never, never>, Record<never, never>>,
    'info-query-detail': RouteRecordInfo<'info-query-detail', '/info-query/detail', Record<never, never>, Record<never, never>>,
    'info-query-result': RouteRecordInfo<'info-query-result', '/info-query/result', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'news-tab': RouteRecordInfo<'news-tab', '/news/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'news-tab-id': RouteRecordInfo<'news-tab-id', '/news/:tab/:id', { tab: ParamValue<true>, id: ParamValue<true> }, { tab: ParamValue<false>, id: ParamValue<false> }>,
    'news-company': RouteRecordInfo<'news-company', '/news/company', Record<never, never>, Record<never, never>>,
    'news-company-id': RouteRecordInfo<'news-company-id', '/news/company/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'news-industry': RouteRecordInfo<'news-industry', '/news/industry', Record<never, never>, Record<never, never>>,
    'news-industry-id': RouteRecordInfo<'news-industry-id', '/news/industry/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'news-technology': RouteRecordInfo<'news-technology', '/news/technology', Record<never, never>, Record<never, never>>,
    'news-technology-id': RouteRecordInfo<'news-technology-id', '/news/technology/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'services-tab': RouteRecordInfo<'services-tab', '/services/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-asia-tab': RouteRecordInfo<'services-certification-asia-tab', '/services/certification/asia/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-australia-tab': RouteRecordInfo<'services-certification-australia-tab', '/services/certification/australia/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-china-tab': RouteRecordInfo<'services-certification-china-tab', '/services/certification/china/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-european-tab': RouteRecordInfo<'services-certification-european-tab', '/services/certification/european/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-north-america-tab': RouteRecordInfo<'services-certification-north-america-tab', '/services/certification/north-america/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-other-tab': RouteRecordInfo<'services-certification-other-tab', '/services/certification/other/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-certification-south-america-tab': RouteRecordInfo<'services-certification-south-america-tab', '/services/certification/south-america/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'services-test-items-chemical': RouteRecordInfo<'services-test-items-chemical', '/services/test-items/chemical', Record<never, never>, Record<never, never>>,
    'services-test-items-efficiency': RouteRecordInfo<'services-test-items-efficiency', '/services/test-items/efficiency', Record<never, never>, Record<never, never>>,
    'services-test-items-emc': RouteRecordInfo<'services-test-items-emc', '/services/test-items/emc', Record<never, never>, Record<never, never>>,
    'services-test-items-laser': RouteRecordInfo<'services-test-items-laser', '/services/test-items/laser', Record<never, never>, Record<never, never>>,
    'services-test-items-reliability': RouteRecordInfo<'services-test-items-reliability', '/services/test-items/reliability', Record<never, never>, Record<never, never>>,
    'services-test-items-rf': RouteRecordInfo<'services-test-items-rf', '/services/test-items/rf', Record<never, never>, Record<never, never>>,
    'services-test-items-safety': RouteRecordInfo<'services-test-items-safety', '/services/test-items/safety', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
